language: python
env:
  global:
  - RS_ACCOUNT=30601
  - RS_HOST=us-3.rightscale.com
  - secure: gsSezHyca347e+f4eUgUg+47N+YDOcAkxT8Uj5t6kC6FGO+EhPmAukp6JDDcVk4zc1AHuBof7bWUC7786POw241b7eKkarcxD4l5FxzFgsqAhxKH8LljfQ0kVTpvxcUd/hPdEaGoG/odQSz94vijEBsQ+YLlwiYKsRnF9Zy4Z4BJCMGZOCwzQNUksFV2KIhmzqicMGVBc6/OEfqhY6zbHhKxvZ3+NAK/1lVOCDjXS9d4MHmagc17tkwi78GdtaXKOZ+6/722BG8gdY00uMMFQaYYom2X5sXxtyuKetUYObiWrKrw7RKtDq0uF44foFpiC4W0nXfR2gIL1Sx+Eyene0V/LbiXmnxGrUMoNHhxuna4ZVRjQBqFrhZxb+eSlUCoKNkTqMj8DMBXv2YsM+HIwd3G1E6QT7BuX4TNrY9VP1FrUlHKzgX/fAeMuBXlWn9vsUbOnYw9GtuTx2Evo7OrX6bDi53tZKaKkaQUXtNmg1TM3+ycCP8MmdeyMis+zcr2HClU7aABPOXlF1jjWMSPx1KOpbzO3E7kT7N3OuL8ver9clfk7Em1Az+eAWzofmMgAh54Kj6P3UCpXu3q+d1oI8Lfw3cNVTYoOSRjYJh74SSEP+sLp++G8jxqd+ONhf58Msf7rjZZyUaxvOZcTUnl6/Jjs266eL1ZmqSvMhjtfQg=
install:
- curl https://binaries.rightscale.com/rsbin/rsc/v6/rsc-linux-amd64.tgz | tar -zxf
  - -O rsc/rsc > rsc
- chmod +x ./rsc
- chmod +x shared/travis_integration/PushCAT.sh
script: shared/travis_integration/PushCAT.sh
