language: python
env:
  global:
  - RS_ACCOUNT=30601
  - RS_HOST=us-3.rightscale.com
  - secure: K5Wx2iuPajoUw9JehrPF5dPdmsvZnSWJ+z58IxUzTr4o8aANOYxdkbVXeykJ4Nn5Y5mnOkRVMLrG1IGWKhxnUzYUSQR70wjknINPR+NCfKmWKpjMrOFklRmHn3NK6KJ2IyA4tTK9prycJlU4SdAJIM+MRSHgC4I+gmSrLBS0puc0qIU7Utwne7e+dLrgA3CUMe19pSsa4hiN2BoDXPvZR/aLJu60XZ8MFVyhC2de/JScaVH5+eJ2CukNOtftxObt50SO/i/FdaUSzLPeUUafqcXzzvvmycUvEzDULSgoBvBtOyLFSAY1PLYfHZ2tdss8tP55+lA5EtsVbqCNKNYq151RRwKqlHn0+ZK9FCu7sRVxbXlXbWN3VZ2QwCPTRWJe9gw3njvhrwbQbBkJng3AiqXvu0vSeNyTdvq9WWeNNSWWld9tC6qUz36r0SrxVWrFC3on4PF/mIaauU3V3p2Jrx2x2B2VTHOQw8jicZXLF20U2nvOrTynjeAFmZ9eChBYPOV0BWTKWCg3rOSa0/8ZEm2p5v58/gtnINnva80kkL4sUoF2eWb4lYZpacME0KJzBuBeRkTkw8X3KJACF6nEZFvoq0OpI5IssZmkSLbHswvtjxRcuUyExw4Ck+OAIkbeYStiil8lnnFpgE1lhaE1FsSBxrhy7ebpzHHykyyuEWw=
install:
- curl https://binaries.rightscale.com/rsbin/rsc/v6/rsc-linux-amd64.tgz | tar -zxf
  - -O rsc/rsc > rsc
- chmod +x ./rsc
- chmod +x shared/travis_integration/PushCAT.sh
script: shared/travis_integration/PushCAT.sh
